version: '3.8'

services:
  ome:
    image: airensoft/ovenmediaengine:latest
    container_name: ome
    environment:
      - OME_HOST_IP=Your.HOST.IP.Address
    ports:
      - "1934:1935"      # RTMP Port
      - "9999:9999/udp"  # SRT Port
      - "9000:9000"      # OME Origin Port
      - "3333:3333"      # LLHLS/WebRTC Signalling Port
      - "3478:3478"      # WebRTC TCP Relay Port
      - "10000-10009:10000-10009/udp"  # WebRTC Candidate Ports
    volumes:
      - ./conf:/opt/ovenmediaengine/bin/origin_conf  # Mount the conf directory
      - ./logs:/var/log/ovenmediaengine             # Mount the logs directory
    restart: unless-stopped
